# Generated by Django 6.0.3 on 2026-09-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_created_at_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
