# Generated by Django 6.0.3 on 2026-09-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_budget_unique_together_alter_budget_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
    ]
